title       = "rdap"
baseURL     = "https://rdap-cli.tamnd.com/"
description = "A command line for rdap."
contentDir  = "content"
outputDir   = "public"
theme       = "tago-doks"
syntaxHighlight = "true"

[params]
github = "https://github.com/tamnd/rdap-cli"
